export const REDIS_CLIENT_TYPE = "REDIS_CLIENT_TYPE";
export const EVENT_BUS = "EVENT_BUS";
export const EVENT_HANDLER = "EVENT_HANDLER";
export const RABBITMQ_CLIENT_TYPE = "RABBITMQ_CLIENT_TYPE";